### ISSUE TITLE
enantiomorphic normalization failed 

### ISSUE THREAD

**Issue by Bandar5543** [neurolabusc/Clinical#10]
Hello,

I am running MR segment-normalize batch with using the enantiomorphic normalization. However, it reaches the last step and failed. 

Failed  'MR segment-normalize'
Error using spm_vol>spm_vol_hdr (line 80)
File "E:\hgg\h01303\NAB\Normalization_tests\Eantrop\c2eh01303_mr2pet.img" does not exist.
In file "C:\Program Files\MATLAB\spm12\spm_vol.m" (v5958), function "spm_vol_hdr" at line 80.
In file "C:\Program Files\MATLAB\spm12\spm_vol.m" (v5958), function "spm_vol" at line 61.
In file "C:\Program Files\MATLAB\spm12\toolbox\Clinical\clinical_mrnormseg12.m" (???), function "extractSub" at line 196.
In file "C:\Program Files\MATLAB\spm12\toolbox\Clinical\clinical_mrnormseg12.m" (???), function "clinical_mrnormseg12" at line 60.
In file "C:\Program Files\MATLAB\spm12\toolbox\Clinical\clinical_mrnormseg_job.m" (???), function "clinical_mrnormseg_job" at line 35.
In file "C:\Program Files\MATLAB\spm12\toolbox\Clinical\tbx_cfg_clinical.m" (???), function "clinical_local_mrnormseg" at line 320.

The following modules did not run:
Failed: MR segment-normalize

**Comment by neurolabusc** [comment]
1. Do the sample images in the `Tutorial` folder process correctly?
2. What files exist in the folder `E:\hgg\h01303\NAB\Normalization_tests\Eantrop`
3. Are your input images single-file NIfTI images (e.g. `h01303_mr2pet.nii`) or 2-file images (`h01303_mr2pet.hdr` and `h01303_mr2pet.img`)?

**Comment by Bandar5543** [comment]
Hi Chris,

Thank you very much for your reply.

1. Yes, the sample images in the Tutorial process correctly.
2. In the directory, I am processing a T1 image with a lesion mask that has
been delineated on the T1. The pipeline works fine until the last step
before it crashes. I can follow up tomorrow from office with screenshot of
the last produced images.
3. My input images are .hdr/.img

Thank you again,
Bandar

**Comment by neurolabusc** [comment]
Why not try with single file NIfTI images. Lots of ways to do this, but I would try
```
 fslmaths h01303_mr2pet.hdr -add 0 nh01303_mr2pet.nii
```
Also, make sure these are valid NIfTI files with a meaningful spatial transform, not older Analyze images with ambiguous spatial orientation.

**Comment by Bandar5543** [comment]
I tried with NIFTI format as you suggested and it works fine.

Thank you a lot!
