### ISSUE TITLE
what is the format of a output file(when a neuroimage been normalized)

### ISSUE THREAD

**Issue by 886ma** [neurolabusc/Clinical#11]
Dear all,
I use the Clinical toobox to normalize my image,but the output result can not been used to do LSM.
The tutorial's output is "bwsLesion.nii",but my output is "bwsrLesion.nii".With it , I can't do use npm(MRIcron) to do LSM. 
CAN anybody tell me  "bwsrLesion.nii" is equcal to  "bwsLesion.nii" or not.
thank you all!

**Comment by neurolabusc** [comment]
The bwsr prefix reveals the processing stages and their order:
 - `b`: brain extracted
 - `w`: warped to normalized space
 - `s`: smoothed: binary image maps can look jagged when interpolated
 -  `r`: realigned (coregistered to a new space).

You will get a `r`ealigned lesion map if your lesion is drawn on a different image than the one used for normalization, so a lesion drawn on a T2, which is realigned to the T1 image which is normalized to standard space. In contrast, realignment is not required if you draw the lesion on the image used for normalization, e.g. the lesion is drawn directly on the T1.

Both output images can be used for subsequent analyses.

**Comment by 886ma** [comment]
thank you very much
