### ISSUE TITLE
Question about Cormack Units

### ISSUE THREAD

**Issue by muschellij2** [neurolabusc/Clinical#2]
In https://github.com/neurolabusc/Clinical/blob/master/clinical_h2c.m#L41, it says 
```matlab
%e.g. -100..+300
```
but that distance is 400, so shouldn't https://github.com/neurolabusc/Clinical/blob/master/clinical_h2c.m#L41 be 
```matlab
kInterestingMidUnits = 400; %e.g. -100..+300
```
?

**Comment by neurolabusc** [comment]
I agree, the value and comments should be the same for the same files, or maybe just have InterestingMidUnits be a function.
```
clinical_h2c.m
clinical_c2h.m
clinical_ctnorm.m
```
For un-enhanced CT, I would suggest
```
kInterestingMidUnits = 200; %e.g. -100..+100
```
while for Gd-enhanced CT I would suggest
```
kInterestingMidUnits = 400; %e.g. -100..+300
```
Probably pretty subtle difference.
