### ISSUE TITLE
clinical_local_ctnorm issue

### ISSUE THREAD

**Issue by Joselisa** [neurolabusc/Clinical#3]
Dear all,
When I tried to run the 'CT normalize' module, I got the following error log:
6-Sep-2019 10:44:35 - Running 'CT normalize'
16-Sep-2019 10:44:35 - Failed  'CT normalize'
Undefined function 'clinical_ctnorm_job' for input arguments of type 'struct'.
In file "/Users/INCE/Documents/MATLAB/spm12/toolbox/Clinical-master/tbx_cfg_clinical.m" (???), function "clinical_local_ctnorm" at line 324.

The following modules did not run:
Failed: CT normalize

I've set the origin manually and I'm not using any lesion masking. Any ideas?

Thanks in advance,
Joselisa

**Comment by neurolabusc** [comment]
Rename the folder 
```
  /Users/INCE/Documents/MATLAB/spm12/toolbox/Clinical-master/
```
to
```
/Users/INCE/Documents/MATLAB/spm12/toolbox/Clinical
```
