### ISSUE TITLE
How to write a normalized brain mask too?

### ISSUE THREAD

**Issue by dkp** [neurolabusc/Clinical#4]
Thanks for creating this useful tool! I have a variety of clinical scans for patients: 
sometimes CT, sometimes a T2, Flair or DWI.  
I'd like to normalize an additional mask (a brain mask) with the Clinicial Toolbox, but I'm afraid I don't see how to add an additional mask to be normalized.  In all cases, the main image to be normalized, the lesion mask and the brain mask start in the same subject space with equivalent coregistration and voxel sizes.
How can I add the brain mask to the list of images to undergo normalization?
Else, how can I find and apply the existing normalization to the brain mask after the fact? 
(sorry, I don't know SPM very well)

Thanks so much,

Dianne

**Comment by neurolabusc** [comment]
Dianne-

For all but the CT, you might want to try MR segment-normalize. It will create brain extracted images 'b' (native space) 'wb' (warped to standard space). It implicitly finds the boundary of the brain. These preserved the original image intensity in the brain, and set regions outside the brain to have intensity zero. 

Most tools will treat this image as a mask (zero versus non zero). If you really want a zero and one mask, you could edit this [script](https://github.com/rordenlab/spmScripts/blob/b0d8001ae97e28e662f2052751669bdb7e4bc68e/nii_zeronan.m), just change the line that reads `img(isnan(img)) = 0;` to be`img(img(:) ~= 0) = 1;`

After normalization, your CT scans should match the image scct.nii, so you could use that as a proxy for a normalized brain mask. If you are normalizing your CT scans to a different resolution than the resolution of that template, you could use [nii_reslice_target.m](https://github.com/rordenlab/spmScripts/blob/b0d8001ae97e28e662f2052751669bdb7e4bc68e/nii_reslice_target.m) to ensure they have the same resolution and bounding box.

**Comment by dkp** [comment]
Thank you very much!  I will give these suggestions a try.

-Dianne
________________________________
