### ISSUE TITLE
‘MR segment-normalize’ module (SPM12)

### ISSUE THREAD

**Issue by luanraguiar** [neurolabusc/Clinical#6]
Dear all,

When I tried to run the ‘MR segment-normalize’ module of the Clinical Toolbox, I got the following error:

###
12-May-2021 16:29:03 - Running ‘MR segment-normalize’
12-May-2021 16:29:03 - Failed ‘MR segment-normalize’
Undefined function ‘clinical_mrnormseg_job’ for input arguments of type ‘struct’.
In file “C:\Users\Neuroimager\Desktop\spm12\toolbox\Clinical-master\tbx_cfg_clinical.m” (???), function “clinical_local_mrnormseg” at line 319.

The following modules did not run:
Failed: MR segment-normalize
###

I would appreciate it very much if anyone could help me on this issue.

Thanks so much,

Luan.

**Comment by neurolabusc** [comment]
Rename the folder
```
C:\Users\Neuroimager\Desktop\spm12\toolbox\Clinical-master
```
as
```
C:\Users\Neuroimager\Desktop\spm12\toolbox\Clinical
```
and restart SPM

**Comment by luanraguiar** [comment]
Thank you so much for your help and attention! 🙏
