### ISSUE TITLE
Can I inverse image to native space after using "CT normalize"?

### ISSUE THREAD

**Issue by Bigsealion** [neurolabusc/Clinical#7]
Thanks for the useful tool!
I have used "CT normalize" to transform a CT image to the template, it's very convenient.
But, I also want to inverse this normalized image back to the native space, have any method to do this?
Thanks!

**Comment by neurolabusc** [comment]
Sure, you can use the SPM Deformations toolbox from the "Toolboxes..." pulldown. You can do this once using the user interface and save your method as a batch script to automate this. Be warned that for nonlinear deformations there are multiple solutions for the reverse transform, so the solution may not be perfect but it is principled.
