### ISSUE TITLE
Smoothing of lesion maps

### ISSUE THREAD

**Issue by kenbridge6** [neurolabusc/Clinical#8]
Thanks for creating this useful tool!
I'd like to ask about MR Segment-Normalization.
The manual says that the outputs are normalized bias corrected anatomical images and binarized, warped, smoothed lesion maps.
How can I get information on parameters of smoothing (smoothing value and threshold, etc.) ?
Is there any ways to modify those parameters?

Thank you for your help in advance!

**Comment by neurolabusc** [comment]
Lesions are drawn as binary images (a voxel is a lesion or it is not). When we reslice a lesion to a new grid, we need to resolve the interpolation. By default, this toolbox blurs [lesions with a 3mm FWHM Gaussian](https://github.com/neurolabusc/Clinical/blob/7a5620ce465c8be4c41bb0c1fdf52444a6f5edbf/clinical_mrnormseg.m#L146) prior to reslicing the data, and then applies a 50% threshold to re-binarize the normalized result (so on average the lesion volume should not be dilated or eroded). Feel free to adjust the parameter as you wish. If all your data is high-resolution isotropic scans, you may consider a less blur. If your lesion is defined using an image with very thick slices, you may want to increase this.

**Comment by kenbridge6** [comment]
Thank you for your introduction! I'll try that!
