### ISSUE TITLE
How to apply the transition matrix to CBF image

### ISSUE THREAD

**Issue by zhuxiao77** [neurolabusc/Clinical#9]
Dear all,

My aim was to 1) coregister the image of CT perfusion to the standard CT template image, and 2) apply the transition matrix from step 1 (cs*.mat) to CBF image which is aligned with the primary CT perfusion image so as to realign the CBF image to template as well. (The reason why I didn’t realign the CBF image directly was that CBF image did not contain anatomical features.)

I successfully coregistered CT perfusion image to standard template based on the manual (the result was quite good), while I had no idea of how to apply the transition matrix (cs*.mat) to the CBF image. I wonder whether you could give me some advice on how to deal with my problems.

Thanks in advance for your help.

Best regards,
Xiao

**Comment by neurolabusc** [comment]
The toolbox assumes that you have the tissue contrast of a structural CT scan. Therefore, it will not do well if you provide it with a CT-perfusion derived measure like CBF, CBV and MTT. You may want to look at [our CTP library](https://github.com/neurolabusc/ctp) that uses the average raw CT scan to guide the normalization of the derived perfusion measures.
